name: Release

on:
  push:
    branches:
    - 'master'
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm i
        npm i -g pkg
        pkg index.js --targets node14-win-x64,node14-macos-x64,node14-linux-x64
        ls -la .

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "index-*"
